name: presentation
description: "A new Flutter project." 
publish_to: 'none' 
  
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-142.0.dev <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  image_picker: ^1.0.4
  intl: ^0.18.1  
  path: ^1.8.3
  path_provider: ^2.1.1



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.1  
  import_sorter: ^4.6.0
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4 

 
 
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg 